

---


**<center>Pandit Deendayal Energy University**<br>
**School of Technology**<br>
**Machine Learning Lab (20CP401P)**<br>
**B.Tech-Computer Science & Engineering (Sem-VII)**<br>


Name: Mire Kishorkumar Patel<br>
Roll No.: 19BCP080<br>
Branch: Computer Science & Engineering<br>

Lab 1 Assignment<br>
Python Practice


---


# **MACHINE LEARNING LAB - 1: Python Practice**

**• PROBLEM STATEMENT : Python Practice Assignment**

**Q1.** Write a function that converts a decimal number to binary number.

In [1]:
 # Function to converts decimal number to binary number
def DecimalToBinary(n):
  ans=''
  while n > 1:
    ans = str(n % 2)+ ans
    n = n // 2
  return str(n)+ans

In [6]:
x = int(input("Enter the decimal number: "))
print("Solution: Binary number for \"", x,"\" :", DecimalToBinary(x))

Enter the decimal number: 2
Solution: Binary number for " 2 " : 10


In [7]:
x = int(input("Enter the decimal number: "))
print("Solution: Binary number for \"", x,"\" :", DecimalToBinary(x))

Enter the decimal number: 255
Solution: Binary number for " 255 " : 11111111


**Q2.** Write a function to compute the sigmoid of a vector of values. <br> 
A sigmoid of a real number $x$ is defind as $\sigma(x)$ = $\frac{1}{1+e^-x}$ <br>
For example:
Input: $[x_{1}, x_{2}, x_{3}, x_{4}]$ <br>
Output: $[\sigma{(x_{1})}, \sigma{(x_{2})}, \sigma{(x_{3})}, \sigma{(x_{4})}]$

In [8]:
import numpy as np

# Function to compute the sigmoid of a vector of values
def Sigmoid(n):
  return 1/(1+np.exp(-n))

In [21]:
def solution(n):
  output = []
  for i in n:
    output.append(Sigmoid(float(i)))
  print(output)

In [22]:
n = input("Enter the values: ").split(",")
print("Input: ", n)
print("Output: ",end="")
solution(n)

Enter the values: 1,2.6,3.2
Input:  ['1', '2.6', '3.2']
Output: [0.7310585786300049, 0.9308615796566533, 0.9608342772032357]


**Q3.** Write a function to compute the derivative of the sigmoid function with respect to its input $x$. Here, the $x$ is a vector. <br> 
The derivative of a sigmoid is defined as: $\sigma(x)(1 - \sigma(x))$
<br>
*TRY TO PROVE THIS IN YOUR COPY*

In [23]:
# Function to compute the derivative of the sigmoid function
def SigmoidDerivation(n):
  return Sigmoid(n) * (1-Sigmoid(n))

In [25]:
def solution(n):
  output = []
  for i in n:
    output.append(SigmoidDerivation(float(i)))
  print(output)

In [26]:
n = input("Enter the values: ").split(",")
print("Input: ", n)
print("Output: ",end="")
solution(n)

Enter the values: 1,2.6,3.2
Input:  ['1', '2.6', '3.2']
Output: [0.19661193324148185, 0.06435829917577342, 0.03763176895457135]


**Q4.** Write a function to normalize the rows of a matrix. After applying this function to an input matrix $x$ of size $m \times n$, each row of $x$ should be a vector of unit length.

In [ ]:
def nor(n):
  y = np.linalg.norm(n, axis=1)
  return np.divide(n.T, y).T

In [ ]:
nor(np.array([[1,2,3],[3,2,4]]))

array([[0.26726124, 0.53452248, 0.80178373],
       [0.55708601, 0.37139068, 0.74278135]])

**Q5.** Write a program which can map() and filter() to make a list whose elements are cube of even numbers in a list.

In [27]:
def CubeOfEvens(n):
  return list(map(lambda x:x**3, filter(lambda x:x%2==0, n)))

In [31]:
x = [1,2,3,4,5,6,7]
print("Input:", x)
print("Output: ", end="")
CubeOfEvens(x)

Input: [1, 2, 3, 4, 5, 6, 7]
Output: 

[8, 64, 216]


**Q6.** consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students <br>
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
import numpy as np

Students= np.array(['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'])
Marks = np.array([45, 78, 12, 14, 48, 43, 47, 98, 35, 80])

print("Students =",Students)
print("Marks =",Marks)

Students = ['student1' 'student2' 'student3' 'student4' 'student5' 'student6'
 'student7' 'student8' 'student9' 'student10']
Marks = [45 78 12 14 48 43 47 98 35 80]


In [ ]:
x = np.argsort(Marks)
x = x[::-1]
# print(x)
print("Solution-a :")
print(Students[x[:5]])
print(Marks[x[:5]])

Solution-a :
['student8' 'student10' 'student2' 'student5' 'student7']
[98 80 78 48 47]


In [ ]:
x = x[::-1]
# print(x)
print("Solution-b :")
print(Students[x[:5]])
print(Marks[x[:5]])

Solution-b :
['student3' 'student4' 'student9' 'student6' 'student1']
[12 14 35 43 45]


In [ ]:
start = len(Students)//2//2
stop = len(Students)//2 + start
print("Solution-c :")
print(Students[x[start:stop]])
print(Marks[x[start:stop]])

Solution-c :
['student9' 'student6' 'student1' 'student7' 'student5']
[35 43 45 47 48]


**Q7.** consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<brs (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$>cosine distance between two point
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
# Function for cosine distance
def CosineDist(x, p):
    return np.arccos(np.divide((x[0]*p[0]+x[1]*p[1]), np.sqrt(x[0]**2+x[1]**2)*np.sqrt(p[0]**2+p[1]**2)))

CosineDist((1,2), (3, -4))

2.0344439357957027

In [ ]:
# Function for cosine distance
def CosineDist(x, y, p, q):
    return np.arccos(np.divide((x*p+y*q), np.sqrt(x**2+y**2)*np.sqrt(p**2+q**2)))

x = np.array([1,3,-1,6,0,-5,-1,6,1])
y = np.array([2,4,1,-7,6,-8,-1,0,-1])
p, q = 3, -4

dist = CosineDist(x, y, p, q)
dist_arg = dist.argsort()

x[dist_arg[:5]]
y[dist_arg[:5]]
z = map(lambda a, b: (a, b), x[dist_arg[:5]], y[dist_arg[:5]])
list(z)

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]

**Q8:** Given two sentences S1, S2
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a matrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
def Func(x, y):
    z = map(lambda a, b: a*np.log10(b)+(1-a)*np.log10(1-b), x, y)
    z = np.array(list(z))

    return z.sum()/len(x)*-1

a = np.array([1,0,0,0,0,1,1,1])
b = np.array([0.4, 0.5, 0.9, 0.3, 0.6, 0.1, 0.9, 0.8])
Func(a, b)

0.42430993457031635